<a href="https://colab.research.google.com/github/aleenalasarin/Machine-Learning-Project/blob/main/Loan_onehotencoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/LoanApprovalPrediction.csv')
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [99]:
df.drop(['Loan_ID'],axis=1,inplace=True)

In [100]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [101]:
df.tail()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [102]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [103]:
df.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [104]:
x=df['Gender'].mode()[0]
x
y=df['Married'].mode()[0]
y
z=df['Dependents'].mode()[0]
z
a=df['Self_Employed'].mode()[0]
a
b=df['LoanAmount'].mean()
b
c=df['Loan_Amount_Term'].mean()
c
d=df['Credit_History'].mean()
d

0.8421985815602837

In [105]:
df['Gender'].fillna(x,inplace=True)
df['Married'].fillna(y,inplace=True)
df['Dependents'].fillna(z,inplace=True)
df['Self_Employed'].fillna(a,inplace=True)
df['LoanAmount'].fillna(b,inplace=True)
df['Loan_Amount_Term'].fillna(c,inplace=True)
df['Credit_History'].fillna(d,inplace=True)
df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [106]:
df.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [107]:
df['Gender'].value_counts()

Male      502
Female    112
Name: Gender, dtype: int64

In [108]:
df['Married'].value_counts()

Yes    401
No     213
Name: Married, dtype: int64

In [109]:
# no need of array when we do onehot encoding
x=df.iloc[:,:-1]
x

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban
1,Male,Yes,1,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban
4,Male,No,0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.000000,360.0,1.0,Rural
610,Male,Yes,3+,Graduate,No,4106,0.0,40.000000,180.0,1.0,Rural
611,Male,Yes,1,Graduate,No,8072,240.0,253.000000,360.0,1.0,Urban
612,Male,Yes,2,Graduate,No,7583,0.0,187.000000,360.0,1.0,Urban
613,Female,No,0,Graduate,Yes,4583,0.0,133.000000,360.0,0.0,Semiurban

In [110]:
y=df.iloc[:,-1]
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object

In [111]:
# onehot encoding
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
col_trans=make_column_transformer((OneHotEncoder(handle_unknown='ignore'),['Gender','Married','Dependents','Education','Self_Employed','Property_Area']),remainder='passthrough')
x=col_trans.fit_transform(x)
x

array([[  0.        ,   1.        ,   1.        , ..., 146.41216216,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 128.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ...,  66.        ,
        360.        ,   1.        ],
       ...,
       [  0.        ,   1.        ,   0.        , ..., 253.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 187.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   1.        , ..., 133.        ,
        360.        ,   0.        ]])

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[  0.        ,   1.        ,   0.        , ..., 181.        ,
        360.        ,   0.        ],
       [  0.        ,   1.        ,   0.        , ..., 155.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ..., 134.        ,
        360.        ,   1.        ],
       ...,
       [  1.        ,   0.        ,   1.        , ...,  30.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   0.        , ..., 146.41216216,
        240.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 146.41216216,
        360.        ,   1.        ]])

In [121]:
x_test

array([[  0.        ,   1.        ,   0.        , ..., 228.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 130.        ,
        360.        ,   0.84219858],
       [  0.        ,   1.        ,   0.        , ..., 158.        ,
        360.        ,   1.        ],
       ...,
       [  0.        ,   1.        ,   0.        , ..., 187.        ,
        180.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 139.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   0.        , ..., 105.        ,
        360.        ,   0.        ]])

In [122]:
y_train

553    N
601    Y
261    Y
496    Y
529    Y
      ..
71     Y
106    Y
270    Y
435    Y
102    Y
Name: Loan_Status, Length: 429, dtype: object

In [123]:
y_test

350    Y
377    Y
163    Y
609    Y
132    Y
      ..
380    Y
446    Y
144    Y
290    Y
353    N
Name: Loan_Status, Length: 185, dtype: object

In [124]:
# normalizaion
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.49343516,  0.49343516, -0.77507823, ...,  0.40368493,
         0.31151435, -2.46213899],
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.09632945,
         0.31151435,  0.4400635 ],
       [-0.49343516,  0.49343516,  1.29019234, ..., -0.15191921,
         0.31151435,  0.4400635 ],
       ...,
       [ 2.02660871, -2.02660871,  1.29019234, ..., -1.38134113,
         0.31151435,  0.4400635 ],
       [ 2.02660871, -2.02660871, -0.77507823, ..., -0.00519051,
        -1.45037962,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.00519051,
         0.31151435,  0.4400635 ]])

In [127]:
x_test

array([[-0.49343516,  0.49343516, -0.77507823, ...,  0.95928907,
         0.31151435,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.19920467,
         0.31151435, -0.01790817],
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.13179354,
         0.31151435,  0.4400635 ],
       ...,
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.47461312,
        -2.33132661,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.09281238,
         0.31151435,  0.4400635 ],
       [ 2.02660871, -2.02660871, -0.77507823, ..., -0.49473878,
         0.31151435, -2.46213899]])

In [129]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst=[knn,base,model]

In [130]:
for i in lst:
  print("model name is...",i)
  i.fit(x_train,y_train)
  print("prediction value...")
  y_pred=i.predict(x_test)
  print(y_pred)
  print("confusion matrix is..")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score is....")
  print(accuracy_score(y_test,y_pred))

Model name is KNeighborsClassifier(n_neighbors=7)
Prediction value is........
['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N']
Confusion matrix....
[[ 17  48]
 [ 10 110]]
Accuracy score is.....
0.6864864864864865
Model name is GaussianNB()
Prediction value is........
['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N'
 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N']
Confusion matrix....
[[ 28  37]
 [  3 117]]
Accuracy score is.....
0.7837837837837838
Model name is SVC()
Prediction value is........
['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'N' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'N' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N'
 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N']
Confusion matrix....
[[ 27  38]
 [  2 118]]
Accuracy score is.....
0.7837837837837838

In [131]:
from sklearn.metrics import classification_report
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           N       0.93      0.42      0.57        65
           Y       0.76      0.98      0.86       120

    accuracy                           0.78       185
   macro avg       0.84      0.70      0.71       185
weighted avg       0.82      0.78      0.76       185